$(function () {
    $('.nav-tabs a').click(function (e) {
        e.preventDefault();
        $(this).tab('show');
    });
});

$(document).ready(function() {
    if ($(window).width() < 1280) {
        $('#header').css({ 'left': (0 - $(window).scrollLeft()) + 'px' });
    }
    $(window).scroll(function() {
        if ($(window).width() < 1280) {
            $('#header').css({ 'left': (0 - $(window).scrollLeft()) + 'px' });
        }
        else {
            $('#header').css({ 'left': '0px' });
        }
    });
    $('.accordion-body').addClass('collapse');

    $(".accordion-heading").click(function() {
        // Reset them
        $(this).removeClass("active");
        $(".accordion-heading").removeClass("active");
        // Add to the clicked one only
        $(this).addClass("active");
        Cufon.refresh();
    });

    $('.download_list li:last').addClass('last');

    $('.privacy-page section:odd').each(function(){
        $(this).addClass("odd");
        $(this).wrap('<div class="bottom_section" />');
        $(this).wrap('<div class="top_section" />');
    });
    $('.help_pg .product-wrap section:odd').each(function(){
        $(this).addClass("odd");
        $(this).wrap('<div class="bottom_section" />');
        $(this).wrap('<div class="top_section" />');
    });

    $('.newsletter a').click(function(){
        $('.newsletter a').removeClass('active');
        $(this).addClass('active');
        if( $(this).hasClass('subscribe') ) {
            $(this).parent().find('input').val('yes');

        } else {
            $(this).parent().find('input').val('no');
        }
        Cufon.refresh();
    });


    $('#forgot_user, #forgot_pass').click(function(){
        $('#myModal').modal('hide');
        $('#myModal2').modal('show');
    });

    $('#cancel_reset_top, #cancel_reset').click(function(){
        $('#myModal2').modal('hide');
        $('#myModal').modal('show');
    });



    $('.flexslider').flexslider({
        namespace: "flex-",             //{NEW} String: Prefix string attached to the class of every element generated by the plugin
        selector: ".slides > li",       //{NEW} Selector: Must match a simple pattern. '{container} > {slide}' -- Ignore pattern at your own peril
        animation: "fade",              //String: Select your animation type, "fade" or "slide"
        easing: "swing",               //{NEW} String: Determines the easing method used in jQuery transitions. jQuery easing plugin is supported!
        direction: "horizontal",        //String: Select the sliding direction, "horizontal" or "vertical"
        reverse: false,                 //{NEW} Boolean: Reverse the animation direction
        animationLoop: true,             //Boolean: Should the animation loop? If false, directionNav will received "disable" classes at either end
        smoothHeight: false,            //{NEW} Boolean: Allow height of the slider to animate smoothly in horizontal mode
        startAt: 0,                     //Integer: The slide that the slider should start on. Array notation (0 = first slide)
        slideshow: true,                //Boolean: Animate slider automatically
        slideshowSpeed: 3000,           //Integer: Set the speed of the slideshow cycling, in milliseconds
        animationSpeed: 600,            //Integer: Set the speed of animations, in milliseconds
        initDelay: 0,                   //{NEW} Integer: Set an initialization delay, in milliseconds
        randomize: false,               //Boolean: Randomize slide order

        // Usability features
        pauseOnAction: true,            //Boolean: Pause the slideshow when interacting with control elements, highly recommended.
        pauseOnHover: false,            //Boolean: Pause the slideshow when hovering over slider, then resume when no longer hovering
        useCSS: false,                   //{NEW} Boolean: Slider will use CSS3 transitions if available
        touch: true,                    //{NEW} Boolean: Allow touch swipe navigation of the slider on touch-enabled devices
        video: true,                   //{NEW} Boolean: If using video in the slider, will prevent CSS3 3D Transforms to avoid graphical glitches

        // Primary Controls
        controlNav: true,               //Boolean: Create navigation for paging control of each clide? Note: Leave true for manualControls usage
        directionNav: false,             //Boolean: Create navigation for previous/next navigation? (true/false)

        // Secondary Navigation
        keyboard: false,                 //Boolean: Allow slider navigating via keyboard left/right keys
        multipleKeyboard: false,        //{NEW} Boolean: Allow keyboard navigation to affect multiple sliders. Default behavior cuts out keyboard navigation with more than one slider present.
        mousewheel: false,              //{UPDATED} Boolean: Requires jquery.mousewheel.js (https://github.com/brandonaaron/jquery-mousewheel) - Allows slider navigating via mousewheel
        pausePlay: false,               //Boolean: Create pause/play dynamic element
        pauseText: 'Pause',             //String: Set the text for the "pause" pausePlay item
        playText: 'Play',               //String: Set the text for the "play" pausePlay item

        // Special properties
        controlsContainer: "",          //{UPDATED} Selector: USE CLASS SELECTOR. Declare which container the navigation elements should be appended too. Default container is the FlexSlider element. Example use would be ".flexslider-container". Property is ignored if given element is not found.
        manualControls: "",             //Selector: Declare custom control navigation. Examples would be ".flex-control-nav li" or "#tabs-nav li img", etc. The number of elements in your controlNav should match the number of slides/tabs.
        sync: "",                       //{NEW} Selector: Mirror the actions performed on this slider with another slider. Use with care.
        asNavFor: "",                   //{NEW} Selector: Internal property exposed for turning the slider into a thumbnail navigation for another slider

        // Carousel Options
        itemWidth: 0,                   //{NEW} Integer: Box-model width of individual carousel items, including horizontal borders and padding.
        itemMargin: 0,                  //{NEW} Integer: Margin between carousel items.
        minItems: 0,                    //{NEW} Integer: Minimum number of carousel items that should be visible. Items will resize fluidly when below this.
        maxItems: 0,                    //{NEW} Integer: Maxmimum number of carousel items that should be visible. Items will resize fluidly when above this limit.
        move: 0,                        //{NEW} Integer: Number of carousel items that should move on animation. If 0, slider will move all visible items.

        // Callback API
        start: function(){},            //Callback: function(slider) - Fires when the slider loads the first slide
        before: function(){},           //Callback: function(slider) - Fires asynchronously with each slider animation
        after: function(){},            //Callback: function(slider) - Fires after each slider animation completes
        end: function(){},              //Callback: function(slider) - Fires when the slider reaches the last slide (asynchronous)
        added: function(){},            //{NEW} Callback: function(slider) - Fires after a slide is added
        removed: function(){}
    });

    $(window).resize(function(){
        var w_width = $(window).width();
        var items_count = Math.floor(w_width/194);
        var it_c = $('.thumb_list > li').length;

        var ul_width1 = items_count*194;
        var ul_width2 = it_c*194;

        if(ul_width1>ul_width2){
            var ul_width = ul_width2;
        } else {
            var ul_width = ul_width1;
        }
        var margin_left = (w_width - ul_width)/2;
        $('.thumb_list').css({'width':w_width-margin_left,'margin-left':margin_left});
    });
    $(window).resize();

    Cufon.replace('#nav li a, #user_nav a, .nav2 a, .nav3 a, .newsletter a, #myModal .nav a,.accordion-toggle, .accordion-toggle span', {hover: true}); // Requires a selector engine for IE 6-7, see above
    Cufon.replace('.thumb_list .title, #home_events .title, .event .event_date, #q_club .title, #left_nav a, #right_nav a, #login .control-label, #submit, #cancel, #cancel_login, #cancel_login, .page-title, label,#images .product-title, #buy_sample, #i_quote, .prod_layout h2, .dinpro'); // Requires a selector engine for IE 6-7, see above
    Cufon.now();

    $(".nav-tabs li a").click(function() {
        Cufon.refresh();
    });
});